package multipart

import (
	"fmt"
	"io"
	"mime/multipart"
	"net/textproto"
	"os"
	"path/filepath"
	"strings"

	"github.com/ryanfowler/fetch/internal/core"
)

// Multipart builds replayable multipart request bodies.
type Multipart struct {
	fields      []core.KeyVal[string]
	files       []fileSnapshot
	initErr     error
	boundary    string
	contentType string
}

type fileSnapshot struct {
	path string
	info os.FileInfo
}

// NewMultipart returns a Multipart using the provided key/values.
func NewMultipart(kvs []core.KeyVal[string]) *Multipart {
	if len(kvs) == 0 {
		return nil
	}

	mpw := multipart.NewWriter(io.Discard)
	fields := append([]core.KeyVal[string](nil), kvs...)
	boundary := mpw.Boundary()
	files := make([]fileSnapshot, len(fields))
	var initErr error
	for i, field := range fields {
		if !strings.HasPrefix(field.Val, "@") {
			continue
		}
		path := field.Val[1:]
		info, err := os.Stat(path)
		if err != nil {
			initErr = err
			continue
		}
		if !info.Mode().IsRegular() {
			initErr = fmt.Errorf("multipart file is not a regular file: %s", path)
			continue
		}
		files[i] = fileSnapshot{path: path, info: info}
	}

	return &Multipart{
		fields:      fields,
		files:       files,
		initErr:     initErr,
		boundary:    boundary,
		contentType: mpw.FormDataContentType(),
	}
}

// Open returns a fresh multipart request body stream.
func (m *Multipart) Open() (io.ReadCloser, error) {
	if m.initErr != nil {
		return nil, m.initErr
	}
	// Create a pipe and asynchronously write to it in a goroutine.
	reader, writer := io.Pipe()
	mpw := multipart.NewWriter(writer)
	if err := mpw.SetBoundary(m.boundary); err != nil {
		_ = reader.CloseWithError(err)
		_ = writer.CloseWithError(err)
		return nil, err
	}

	go func() {
		var err error
		defer func() {
			if err != nil {
				_ = writer.CloseWithError(err)
				return
			}
			if err = mpw.Close(); err != nil {
				_ = writer.CloseWithError(err)
				return
			}
			_ = writer.Close()
		}()

		for i, kv := range m.fields {
			if !strings.HasPrefix(kv.Val, "@") {
				if err = mpw.WriteField(sanitizeHeaderParameter(kv.Key), kv.Val); err != nil {
					return
				}
				continue
			}

			// Form part is a file.
			if err = writeFilePart(mpw, kv.Key, m.files[i]); err != nil {
				return
			}
		}
	}()

	return reader, nil
}

// ContentType returns the Content-Type header value to use for this request.
func (m *Multipart) ContentType() string {
	return m.contentType
}

// writes the multipart file part and returns any error encountered.
func writeFilePart(mpw *multipart.Writer, key string, snapshot fileSnapshot) error {
	filename := snapshot.path
	current, err := os.Stat(filename)
	if err != nil {
		return err
	}
	if !current.Mode().IsRegular() || !os.SameFile(snapshot.info, current) || current.Size() != snapshot.info.Size() {
		return fmt.Errorf("multipart file changed: %s", filename)
	}
	f, err := os.Open(filename)
	if err != nil {
		return err
	}
	defer f.Close()
	opened, err := f.Stat()
	if err != nil {
		return err
	}
	if !opened.Mode().IsRegular() || !os.SameFile(snapshot.info, opened) || opened.Size() != snapshot.info.Size() {
		return fmt.Errorf("multipart file changed: %s", filename)
	}

	_, ct, err := core.DetectContentType(f, filename)
	if err != nil {
		return err
	}
	if _, err := f.Seek(0, io.SeekStart); err != nil {
		return err
	}

	headers := textproto.MIMEHeader{}
	headers.Set("Content-Disposition", multipart.FileContentDisposition(
		sanitizeHeaderParameter(key), sanitizeHeaderParameter(filepath.Base(filename))))
	headers.Set("Content-Type", ct)

	w, err := mpw.CreatePart(headers)
	if err != nil {
		return err
	}

	_, err = io.Copy(w, &exactFileReader{
		file:      f,
		remaining: snapshot.info.Size(),
		expected:  snapshot.info.Size(),
		path:      filename,
		identity:  snapshot.info,
	})
	return err
}

// sanitizeHeaderParameter keeps user-controlled multipart names and
// filenames inside the quoted Content-Disposition parameters generated by the
// standard library. Rejecting the input would be surprising for a CLI flag;
// replacing bytes that could terminate or inject a parameter preserves the
// upload while making the resulting header unambiguous.
func sanitizeHeaderParameter(value string) string {
	var b strings.Builder
	b.Grow(len(value))
	for _, r := range value {
		switch r {
		case '\r', '\n', '\\', '"':
			b.WriteByte('_')
		default:
			if r < 0x20 || r == 0x7f {
				b.WriteByte('_')
			} else {
				b.WriteRune(r)
			}
		}
	}
	if b.Len() == 0 {
		return "_"
	}
	return b.String()
}

type exactFileReader struct {
	file      *os.File
	remaining int64
	expected  int64
	path      string
	identity  os.FileInfo
}

func (r *exactFileReader) Read(p []byte) (int, error) {
	if r.remaining == 0 {
		info, err := os.Stat(r.path)
		if err != nil {
			return 0, err
		}
		if info.Size() != r.expected || !info.Mode().IsRegular() || !os.SameFile(r.identity, info) {
			return 0, fmt.Errorf("multipart file changed while reading: %s", r.path)
		}
		return 0, io.EOF
	}
	if int64(len(p)) > r.remaining {
		p = p[:r.remaining]
	}
	n, err := r.file.Read(p)
	r.remaining -= int64(n)
	if err == io.EOF && r.remaining > 0 {
		return n, fmt.Errorf("multipart file ended before its expected length: %s", r.path)
	}
	return n, err
}
