package image

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"image"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/ryanfowler/fetch/internal/core"
)

const (
	imagePathArg           = "IMAGE_PATH"
	externalAdapterTimeout = 10 * time.Second
	maxAdapterStdoutBytes  = 64 << 20
)

type adaptor struct {
	name       string
	args       []string
	env        []string
	outputFile bool
	preflight  bool
}

// Keep these command lines intentionally small and fixed. The image path is
// generated by fetch and is substituted as one argv element; it is never
// interpreted by a shell. Each adapter produces one bounded JPEG result.
var adaptors = []adaptor{
	{
		name:       "vips",
		args:       []string{"copy", imagePathArg, "OUTPUT_PATH"},
		env:        []string{"VIPS_MAX_MEM=512MB", "VIPS_CONCURRENCY=1"},
		outputFile: true,
		preflight:  true,
	},
	{
		name: "magick",
		args: []string{"-limit", "area", "67108864", "-limit", "memory", "512MiB", imagePathArg, "-flatten", "jpg:-"},
		env:  []string{"MAGICK_MEMORY_LIMIT=512MiB", "MAGICK_TIME_LIMIT=10000", "MAGICK_THREAD_LIMIT=1"},
	},
	{
		name: "ffmpeg",
		args: []string{"-nostdin", "-v", "error", "-max_pixels", "67108864", "-i", imagePathArg, "-map", "0:v:0", "-frames:v", "1", "-f", "image2pipe", "-c:v", "mjpeg", "pipe:1"},
	},
}

func decodeWithAdaptors(ctx context.Context, b []byte) (image.Image, error) {
	// MkdirTemp creates a private 0700 directory. The input file is also
	// exclusive and owner-readable so a concurrent process cannot replace it
	// or observe the source image through a predictable name.
	dir, err := os.MkdirTemp("", "fetch-image-")
	if err != nil {
		return nil, fmt.Errorf("create image adapter directory: %w", err)
	}
	defer os.RemoveAll(dir)

	imgPath := filepath.Join(dir, "input")
	file, err := os.OpenFile(imgPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		return nil, fmt.Errorf("create image adapter input: %w", err)
	}
	_, writeErr := file.Write(b)
	closeErr := file.Close()
	if writeErr != nil {
		return nil, fmt.Errorf("write image adapter input: %w", writeErr)
	}
	if closeErr != nil {
		return nil, fmt.Errorf("close image adapter input: %w", closeErr)
	}

	var attempted []string
	var failures []string
	for _, adapter := range adaptors {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		path, lookErr := exec.LookPath(adapter.name)
		if lookErr != nil {
			continue
		}
		attempted = append(attempted, adapter.name)
		if adapter.preflight {
			if runErr := checkAdapterDimensions(ctx, imgPath); runErr != nil {
				failures = append(failures, adapter.name+": "+shortAdapterError(runErr))
				continue
			}
		}

		img, runErr := decodeAdaptor(ctx, imgPath, path, adapter)
		if runErr == nil {
			return img, nil
		}
		failures = append(failures, adapter.name+": "+shortAdapterError(runErr))
		if err := ctx.Err(); err != nil {
			return nil, err
		}
	}

	if len(attempted) == 0 {
		return nil, errors.New("no external image adapter is available (tried vips, magick, ffmpeg)")
	}
	return nil, fmt.Errorf("external image adapters failed: %s", strings.Join(failures, "; "))
}

func checkAdapterDimensions(parent context.Context, imgPath string) error {
	headerPath, err := exec.LookPath("vipsheader")
	if err != nil {
		return errors.New("vipsheader is unavailable for dimension validation")
	}
	data, err := runContainedCommand(parent, headerPath, []string{"-f", "width", "-f", "height", imgPath}, 128)
	if err != nil {
		return fmt.Errorf("read image dimensions: %w", err)
	}
	values := strings.Fields(string(data))
	if len(values) != 2 {
		return errors.New("vipsheader returned invalid dimensions")
	}
	width, err := strconv.Atoi(values[0])
	if err != nil {
		return fmt.Errorf("invalid image width: %w", err)
	}
	height, err := strconv.Atoi(values[1])
	if err != nil {
		return fmt.Errorf("invalid image height: %w", err)
	}
	return validateImageConfig(image.Config{Width: width, Height: height})
}

func runContainedCommand(parent context.Context, path string, args []string, maxOutput int64) ([]byte, error) {
	ctx, cancel := context.WithTimeout(parent, externalAdapterTimeout)
	defer cancel()
	cmd := exec.Command(path, args...)
	if err := configureProcess(cmd); err != nil {
		return nil, err
	}
	cmd.Stdin = nil
	cmd.Stderr = io.Discard
	var output cappedOutput
	output.max = maxOutput
	output.onLimit = func() { terminateProcessTree(cmd) }
	cmd.Stdout = &output
	if err := cmd.Start(); err != nil {
		releaseProcess(cmd)
		return nil, err
	}
	if err := attachProcess(cmd); err != nil {
		terminateProcessTree(cmd)
		_ = cmd.Wait()
		releaseProcess(cmd)
		return nil, err
	}
	defer releaseProcess(cmd)
	waitDone := make(chan error, 1)
	go func() { waitDone <- cmd.Wait() }()
	select {
	case err := <-waitDone:
		if output.limitHit() {
			return nil, core.LimitError{Subsystem: "image adapter dimension output", Limit: maxOutput}
		}
		if err != nil {
			return nil, err
		}
		return output.Bytes(), nil
	case <-ctx.Done():
		terminateProcessTree(cmd)
		<-waitDone
		if parent.Err() != nil {
			return nil, parent.Err()
		}
		return nil, fmt.Errorf("adapter timed out after %s", externalAdapterTimeout)
	}
}

func decodeAdaptor(parent context.Context, imgPath, path string, adapter adaptor) (image.Image, error) {
	// Always impose an adapter deadline. WithTimeout keeps a narrower request
	// or cancellation deadline when the parent already has one.
	ctx, cancel := context.WithTimeout(parent, externalAdapterTimeout)
	defer cancel()
	if err := ctx.Err(); err != nil {
		return nil, err
	}

	args := slices.Clone(adapter.args)
	outputPath := ""
	if adapter.outputFile {
		outputPath = filepath.Join(filepath.Dir(imgPath), "output-"+adapter.name+".jpg")
	}
	for i, arg := range args {
		switch arg {
		case imagePathArg:
			args[i] = imgPath
		case "OUTPUT_PATH":
			args[i] = outputPath
		}
	}

	cmd := exec.Command(path, args...)
	if err := configureProcess(cmd); err != nil {
		return nil, err
	}
	// A decoder must never be able to consume the fetch process's stdin.
	cmd.Stdin = nil
	cmd.Stderr = io.Discard

	var stdout cappedOutput
	stdout.max = maxAdapterStdoutBytes
	stdout.onLimit = func() { terminateProcessTree(cmd) }
	cmd.Stdout = &stdout
	if len(adapter.env) > 0 {
		cmd.Env = mergedAdapterEnvironment(adapter.env)
	}

	if err := cmd.Start(); err != nil {
		releaseProcess(cmd)
		return nil, err
	}
	if err := attachProcess(cmd); err != nil {
		terminateProcessTree(cmd)
		_ = cmd.Wait()
		releaseProcess(cmd)
		return nil, err
	}
	defer releaseProcess(cmd)

	var stopMonitor chan struct{}
	var monitorDone chan struct{}
	if adapter.outputFile {
		stopMonitor = make(chan struct{})
		monitorDone = make(chan struct{})
		go monitorAdapterFile(outputPath, cmd, stopMonitor, monitorDone)
		defer func() {
			close(stopMonitor)
			<-monitorDone
		}()
	}

	waitDone := make(chan error, 1)
	go func() { waitDone <- cmd.Wait() }()

	var runErr error
	select {
	case runErr = <-waitDone:
	case <-ctx.Done():
		terminateProcessTree(cmd)
		<-waitDone
		if errors.Is(ctx.Err(), context.DeadlineExceeded) {
			if parent.Err() != nil {
				return nil, parent.Err()
			}
			return nil, fmt.Errorf("adapter timed out after %s", externalAdapterTimeout)
		}
		return nil, ctx.Err()
	}
	if stdout.limitHit() {
		return nil, core.LimitError{Subsystem: adapter.name + " image adapter output", Limit: maxAdapterStdoutBytes}
	}
	if runErr != nil {
		return nil, runErr
	}
	output := stdout.Bytes()
	var err error
	if adapter.outputFile {
		output, err = readAdapterFile(outputPath)
		if err != nil {
			return nil, err
		}
	}
	if len(output) == 0 {
		return nil, errors.New("adapter produced no image data")
	}
	img, err := decodeImageStd(output)
	if err != nil {
		return nil, fmt.Errorf("adapter output: %w", err)
	}
	return img, nil
}

func mergedAdapterEnvironment(overrides []string) []string {
	env := slices.Clone(os.Environ())
	for _, override := range overrides {
		key, _, ok := strings.Cut(override, "=")
		if !ok || key == "" {
			continue
		}
		env = slices.DeleteFunc(env, func(entry string) bool {
			entryKey, _, hasValue := strings.Cut(entry, "=")
			return hasValue && entryKey == key
		})
		env = append(env, override)
	}
	return env
}

func monitorAdapterFile(path string, cmd *exec.Cmd, stop <-chan struct{}, done chan<- struct{}) {
	defer close(done)
	ticker := time.NewTicker(10 * time.Millisecond)
	defer ticker.Stop()
	for {
		select {
		case <-stop:
			return
		case <-ticker.C:
			info, err := os.Lstat(path)
			if err != nil {
				continue
			}
			if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() || info.Size() > maxAdapterStdoutBytes {
				terminateProcessTree(cmd)
				return
			}
		}
	}
}

func readAdapterFile(path string) ([]byte, error) {
	info, err := os.Lstat(path)
	if err != nil {
		return nil, err
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return nil, errors.New("adapter output is not a regular file")
	}
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	return core.ReadAllLimited(file, maxAdapterStdoutBytes, "image adapter output")
}

func shortAdapterError(err error) string {
	if err == nil {
		return "unknown error"
	}
	// Command errors can include local executable names, but never include
	// adapter stdout. Keep aggregate diagnostics concise and single-line.
	return strings.Join(strings.Fields(err.Error()), " ")
}

type cappedOutput struct {
	bytes.Buffer
	max     int64
	onLimit func()
	once    sync.Once
	hit     bool
}

func (b *cappedOutput) Write(p []byte) (int, error) {
	if b.max < 0 || int64(b.Len()) >= b.max {
		b.hitLimit()
		return 0, core.LimitError{Subsystem: "image adapter output", Limit: b.max}
	}
	remaining := b.max - int64(b.Len())
	if int64(len(p)) > remaining {
		if remaining > 0 {
			_, _ = b.Buffer.Write(p[:remaining])
		}
		b.hitLimit()
		return int(remaining), core.LimitError{Subsystem: "image adapter output", Limit: b.max}
	}
	return b.Buffer.Write(p)
}

func (b *cappedOutput) hitLimit() {
	b.once.Do(func() {
		b.hit = true
		if b.onLimit != nil {
			b.onLimit()
		}
	})
}

func (b *cappedOutput) limitHit() bool { return b.hit }
