[package]
name = "fetch"
version = "0.1.0"
edition = "2021"
description = "fetch is a modern HTTP(S) client for the command line"

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 3
strip = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[build-dependencies]
cc = { version = "1.1.24" }

[dependencies]
ansi_colours = { version = "1.2.3" }
anstyle = { version = "1.0.8" }
base64 = { version = "0.22.1" }
brotli = { version = "6.0.0" }
clap = { version = "4.5.19", features = ["derive"] }
crossterm = { version = "0.28.1" }
duration-string = { version = "0.4.0" }
flate2 = { version = "1.0.34", features = ["zlib"] }
hmac = { version = "0.12.1" }
image = { version = "0.25.2", default-features = false, features = ["jpeg", "png", "tiff"] }
jiff = { version = "0.1.13" }
kamadak-exif = "0.5.5"
libavif-image = { version = "0.14.0", default-features = false, features = ["codec-dav1d"] }
mime = { version = "0.3.17" }
percent-encoding = { version = "2.3.1" }
quick-xml = { version = "0.36.2" }
lazy_static = { version = "1.5.0" }
reqwest = { version = "0.12.8", features = ["blocking", "rustls-tls-native-roots"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", features = ["preserve_order"] }
serde_urlencoded = { version = "0.7.1" }
sha2 = { version = "0.10.8" }
tempfile = { version = "3.13.0" }
termcolor = { version = "1.4.1" }
toml = { version = "0.8.19" }
tree-sitter = { version = "0.23.2" }
tree-sitter-highlight = { version = "0.23.2" }
url = { version = "2.5.2" }
webp = { version = "0.3.0" }
zstd = { version = "0.13.2" }
