[package]
name = "fetch-cli"
version = "0.2.2"
edition = "2021"
description = "fetch is a modern HTTP(S) client for the command line"
authors = ["Ryan Fowler <ryan.fowler19@gmail.com>"]
repository = "https://github.com/ryanfowler/fetch"
categories = ["command-line-utilities"]
keywords = ["http", "https", "client"]
license = "MIT"
include = ["build.rs", "grammars.toml", "/grammars", "/highlights", "/src", "/themes"]

[[bin]]
path = "src/main.rs"
name = "fetch"

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 3
strip = true

[build-dependencies]
cc = { version = "1.2.7" }
serde = { version = "1.0.217", features = ["derive"] }
toml = { version = "0.8.19" }

[dependencies]
ansi_colours = { version = "1.2.3" }
anstyle = { version = "1.0.10" }
base64 = { version = "0.22.1" }
brotli = { version = "7.0.0" }
clap = { version = "4.5.26", features = ["derive"] }
console = { version = "0.15", default-features = false, features = ["ansi-parsing"] }
crossterm = { version = "0.28.1" }
flate2 = { version = "1.0.35", features = ["zlib"] }
hmac = { version = "0.12.1" }
image = { version = "0.25.5", default-features = false, features = ["jpeg", "png", "tiff"] }
indicatif = { version = "0.17.9" }
jiff = { version = "0.1.22" }
kamadak-exif = "0.6.1"
mime = { version = "0.3.17" }
mime_guess = { version = "2.0.5" }
percent-encoding = { version = "2.3.1" }
quick-xml = { version = "0.37.2" }
lazy_static = { version = "1.5.0" }
reqwest = { version = "0.12.12", default-features = false, features = ["blocking", "http2", "macos-system-configuration", "multipart", "rustls-tls-native-roots"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.135", features = ["preserve_order"] }
serde_urlencoded = { version = "0.7.1" }
sha2 = { version = "0.10.8" }
tempfile = { version = "3.15.0" }
termcolor = { version = "1.4.1" }
toml = { version = "0.8.19" }
tree-sitter = { version = "0.24.7" }
tree-sitter-highlight = { version = "0.24.4" }
url = { version = "2.5.4" }
webp = { version = "0.3.0" }
zstd = { version = "0.13.2" }
