# treesitter grammars

[[language]]
name = "html"
files = ["src/parser.c", "src/scanner.c"]
headers = ["src/tag.h", "src/tree_sitter/alloc.h", "src/tree_sitter/array.h", "src/tree_sitter/parser.h"]
revision = "d9219ada6e1a2c8f0ab0304a8bd9ca4285ae0468"
repository = "https://github.com/tree-sitter/tree-sitter-html"

[[language]]
name = "json"
files = ["src/parser.c"]
headers = ["src/tree_sitter/alloc.h", "src/tree_sitter/array.h", "src/tree_sitter/parser.h"]
revision = "4d770d31f732d50d3ec373865822fbe659e47c75"
repository = "https://github.com/tree-sitter/tree-sitter-json"

[[language]]
name = "toml"
files = ["src/parser.c", "src/scanner.c"]
headers = ["src/tree_sitter/parser.h"]
revision = "342d9be207c2dba869b9967124c679b5e6fd0ebe"
repository = "https://github.com/tree-sitter/tree-sitter-toml"

[[language]]
name = "xml"
files = ["xml/src/parser.c", "xml/src/scanner.c"]
headers = ["common/scanner.h", "xml/src/tree_sitter/alloc.h", "xml/src/tree_sitter/array.h", "xml/src/tree_sitter/parser.h"]
revision = "ce150c5be7f617e18ffa2064213e5d9c4cb5d69e"
repository = "https://github.com/tree-sitter-grammars/tree-sitter-xml"

[[language]]
name = "yaml"
files = ["src/parser.c", "src/scanner.c", "src/schema.core.c", "src/schema.json.c"]
headers = ["src/tree_sitter/alloc.h", "src/tree_sitter/array.h", "src/tree_sitter/parser.h"]
revision = "1805917414a9a8ba2473717fd69447277a175fae"
repository = "https://github.com/tree-sitter-grammars/tree-sitter-yaml"
