# Default theme

"attribute" = {}
"boolean" = {}
"comment" = { dimmed = true }
"conceal" = {}
"markup" = "green"
"number" = {}
"property" = { fg = "blue", bold = true }
"property.attribute" = "cyan"
"property.tag" = {}
"string" = "green"
"tag" = { fg = "blue", bold = true }
"type" = { fg = "cyan", bold = true }
