[package]
name = "fetch-automation"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
toml = { version = "0.8.19" }
ureq = { version = "2.10.1" }
